### PR TITLE
Include Model on createCachingMethods loader

### PR DESCRIPTION
**Pull request by edgareler**
Similar to #28, but uses `Model.find().exec()` as promise, and checks if the `collection` parameter is Model.

### CODE REVIEW

**Comment by lorensr** [comment]
Is there a benefit to using exec?

**Comment by edgareler** [comment]
According to Mongoose docs, that [gives you better stack traces](https://mongoosejs.com/docs/promises.html#should-you-use-exec-with-await?).

**Comment by lorensr** [comment]
Sounds good, and thanks for the contribution! Would you mind adding a test to cover the new logic?

**Comment by edgareler** [comment]
Hi @lorensr, I've just included two new ID matchers to the existing tests, which basically covers the Model vs Collection issue.

**Comment by lorensr** [comment]
Thanks again! Published in `0.2.7`

**Pull request merged**
