### PR TITLE
Expose #deleteFromCacheByFields

### PR DESCRIPTION
**Pull request by bitops**
A PR for [this issue](https://github.com/GraphQLGuide/apollo-datasource-mongodb/issues/68). Thanks so much!

### CODE REVIEW

**Comment by bitops** [comment]
@lorensr this fills a big need for me in the API so all feedback welcome!

**Comment by bitops** [comment]
@lorensr any feedback on this PR? If you think this is looking good I am glad to try and give [this bug](https://github.com/GraphQLGuide/apollo-datasource-mongodb/issues/69) another attempt next. (Also, I left you an implementation question on that issue.)

**Comment by lorensr** [comment]
Thanks a lot! I edited your code a little, as well as making a number of other changes in this commit: https://github.com/GraphQLGuide/apollo-datasource-mongodb/commit/90411e3b183cd5b98a53c25d0825e01bc147f485

**Comment by bitops** [comment]
@lorensr a-okay with me! I am glad to see the contribution make it in. Thank you accepting it. 🙏

**Pull request merged**
